name: b2-windows
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - gmp
  - mpfr
  - mpc
  - libboost-devel
  - eigen
  - eigenpy
  - libboost-python-devel
  - scipy
  - wheel
  - build
  - scikit-build-core
