name: b2-windows
channels:
  - conda-forge
  - defaults
dependencies:
  - cmake
  - ccache
  - cxx-compiler
  - ninja
  - numpy
  - gmp
  - mpfr
  - mpc
  - libboost-devel=1.90.0
  - eigen
  - eigenpy
  - libboost-python-devel=1.90.0
  - vs2022_win-64
  - scipy
  - python
  - wheel
  - build
  - scikit-build-core
  - pkg-config
  - git
