name: b2-ubuntu
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - gmp
  - mpfr
  - mpc
  - automake
  - autoconf
  - libtool
  - boost
  - eigen
  - eigenpy
  - libboost-python
  - scipy
  - wheel
  - build
