name: b2-ubuntu
channels:
  - conda-forge
  - defaults
dependencies:
  - gxx==13.3.0
  - numpy
  - gmp
  - mpfr
  - mpc
  - auditwheel
  - automake
  - autoconf
  - libtool
  - libboost=1.90.0
  - eigen
  - eigenpy
  - libboost-python=1.90.0
  - scipy
  - wheel
  - build
  - patchelf
