name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on:
  push:
    branches:
      - 'develop'
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build Binaries for ${{ matrix.os }}-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [
          '3.11.12'
        ]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Build manylinux wheels
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          docker run --rm --network=host -v $(pwd):/io quay.io/pypa/manylinux2014_x86_64 bash -c "
          # Install dependencies
          cd /io
          yum install -y wget gmp-devel mpfr-devel libmpc-devel eigen3-devel libtool
          
          # Build for multiple Python versions
          for PYBIN in /opt/python/cp{39,310,311,312}-*/bin; do
          
          # Upgrade pip and install build tools
          \${PYBIN}/pip install scikit-build-core numpy scipy
          
          # Install boost and eigenpy
          cd /tmp
          wget https://archives.boost.io/release/1.87.0/source/boost_1_87_0.tar.bz2
          bunzip2 boost_1_87_0.tar.bz2
          tar xf boost_1_87_0.tar
          cd boost_1_87_0
          ./bootstrap.sh --prefix=/usr/local --with-python=\${PYBIN}
          ./b2 install
          
          cd /tmp
          wget https://github.com/stack-of-tasks/eigenpy/releases/download/v3.11.0/eigenpy-3.11.0.tar.gz
          tar zxf eigenpy-3.11.0.tar.gz
          cd eigenpy-3.11.0
          mkdir -p bld
          cd bld
          cmake .. -DCMAKE_PREFIX_PATH=/usr/local -DCMAKE_INSTALL_PREFIX=/usr/local -DPYTHON_EXECUTABLE=\${PYBIN}/python
          make install
          
          # Get Python version info
          DIR=$(dirname ${PYBIN})           # /opt/python/cp39-cp39-manylinux2014_x86_64
          PYVER=${DIR##*/}                  # cp39-cp39-manylinux2014_x86_64
          
          # Build wheels & bundle external shared libraries into wheels
          export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH
          \${PYBIN}/pip wheel /io --no-deps -w /io/wheelhouse/
          auditwheel repair pybertini-1.0a8-\${PYVER}.whl --plat manylinux2014_x86_64 -w /io/dist/
          done
          "
      - name: conda-windows
        uses: conda-incubator/setup-miniconda@v3
        if: ${{ startsWith(matrix.os, 'windows') }}
        with:
          activate-environment: b2-windows
          environment-file: environment-win.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - name: Build Windows
        if: ${{ startsWith(matrix.os, 'windows') }}
        shell: pwsh
        #          https://stackoverflow.com/questions/79073953/clang-undefined-symbol-boostarchivearchive-exception
        run: |
          conda info
          conda list

          $env:CC='clang-cl'
          $env:CXX='clang-cl'
          $env:CMAKE_GENERATOR='Ninja'
          $env:CMAKE_PREFIX_PATH="$env:CONDA_PREFIX\Library"

          # Patch boost header to fix clang-cl linker error
          $boostHeader = "$env:CONDA_PREFIX\Library\include\boost\archive\archive_exception.hpp"
          (Get-Content $boostHeader).Replace('public virtual std::exception', 'public std::exception') | Set-Content $boostHeader

          cd ${{github.workspace}}
          pip install build
          python -m build --wheel --no-isolation
      - name: Build MacOS
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: |
          brew install gmp
          brew install mpfr
          brew install libmpc
          brew install eigen@3
          brew install eigenpy
          brew install boost
          brew install boost-python3
          brew install python-setuptools
          
          python3 -m venv venv
          source venv/bin/activate
          pip install numpy scipy wheel build
          cd ${{github.workspace}}
          mkdir build
          cd build
          export CMAKE_PREFIX_PATH="/opt/homebrew/opt/boost@1.85:$CMAKE_PREFIX_PATH"
          cmake ..
          make -j 4

          cd ..
          python3 -m build --wheel
      - name: Upload Builds
        uses: actions/upload-artifact@v4
        with:
          name: built-binary-${{ matrix.os }}
          path: |
            ${{github.workspace}}/dist/*.whl
            ${{github.workspace}}/dist/*.tar.gz
            ${{github.workspace}}/dist/*.zip
            ${{github.workspace}}/build/*.exe
            ${{github.workspace}}/build/*.bin

  publish-to-testpypi:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    needs:
      - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/pybertini

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          verbose: true
          repository-url: https://test.pypi.org/legacy/

  publish-to-pypi:
    name: >-
      Publish Python 🐍 distribution 📦 to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pybertini  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          verbose: true

  github-release:
    name: >-
      Sign the Python 🐍 distribution 📦 with Sigstore
      and upload them to GitHub Release
    if: startsWith(github.ref, 'refs/tags/')  # only publish to release on tag pushes
    needs:
      - publish-to-pypi
    runs-on: ubuntu-latest

    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: >-
            ./dist/*.whl

      - name: Get Newest Changelog
        run: |
          python -c 'import re; from pathlib import Path; text=re.sub("<!--(.*?)-->", "", (Path.cwd() / "CHANGELOG.md").read_text(), flags=re.DOTALL); print(text); start=text.find("_" * 79); (Path.cwd() / "TEMP_CHANGELOG.md").write_text(text[start:text.find("_" * 79, start+1)])'

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body_path: ./TEMP_CHANGELOG.md
          files: |
            dist/*.*
