name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on: push
#  push:
#    tags:
#      - 'v*'

jobs:
  build:
    name: Build Binaries for ${{ matrix.os }}-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [
          '3.10',
          'pypy-3.9',
        ]
        exclude:
          - os: windows-latest
            python-version: 'pypy-3.9'
          - os: macos-latest
            python-version: 'pypy-3.9'
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
#      - uses: conda-incubator/setup-miniconda@v3
#        with:
#          activate-environment: b2
#          environment-file: environment.yml
#          python-version: ${{ matrix.python-version }}
#          auto-activate-base: false
#      - name: Build (Posix and Windows)
#        if: ${{ !startsWith(matrix.python-version, 'pypy') && !startsWith(matrix.os, 'macos')}}
#        shell: bash -el {0}
#        run: |
#          conda info
#          conda list
#          cd ${{github.workspace}}/core
#          mkdir build
#          cd build
#          cmake .. -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/b2/build -DCMAKE_PREFIX_PATH=$CONDA_PREFIX
#          make -j 4
#          make install
#
#          cd ${{github.workspace}}/python
#          mkdir build
#          cd build
#          cmake .. -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/b2/build -DCMAKE_PREFIX_PATH=$CONDA_PREFIX
#          make -j 4
#          make install
#
#          cd ..
#          pip install twine wheel
#          python3 -m pip install -e .
#          python3 setup.py bdist
#      - name: Install necessary dependencies (Posix)
#        if: ${{ !startsWith(matrix.python-version, 'pypy') && startsWith(matrix.os, 'ubuntu') }}
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y libgmp3-dev libmpfr-dev libmpc-dev libeigen3-dev
#      - name: Install necessary dependencies (Posix)
#        if: ${{ !startsWith(matrix.python-version, 'pypy') && startsWith(matrix.os, 'ubuntu')}}
#        shell: bash -l {0}
#        run: |
#          $CONDA/bin/conda env update --file environment.yml --name base
#          $CONDA/bin/conda activate base
#          cd ${{github.workspace}}/core
#          mkdir build
#          cd build
#          cmake .. -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/b2/build -DCMAKE_PREFIX_PATH=$CONDA_PREFIX
#          make -j 4
#          make install
#
#          cd ${{github.workspace}}/python
#          mkdir build
#          cd build
#          cmake .. -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/b2/build -DCMAKE_PREFIX_PATH=$CONDA_PREFIX
#          make -j 4
#          make install
#
#          cd ..
#          pip install twine wheel
#          python3 -m pip install -e .
#          python3 setup.py bdist
#      - name: Install necessary dependencies (Windows)
#        if: ${{ !startsWith(matrix.python-version, 'pypy') && startsWith(matrix.os, 'windows')}}
#        run: |
#          C:\Miniconda\condabin\conda.bat env update --file environment.yml --name base
#          C:\Miniconda\condabin\conda.bat init powershell
#          C:\Miniconda\condabin\conda.bat activate base
#          cd ${{github.workspace}}/core
#          mkdir build
#          cd build
#          cmake .. -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/b2/build -DCMAKE_PREFIX_PATH=$CONDA_PREFIX
#          make -j 4
#          make install
#
#          cd ${{github.workspace}}/python
#          mkdir build
#          cd build
#          cmake .. -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/b2/build -DCMAKE_PREFIX_PATH=$CONDA_PREFIX
#          make -j 4
#          make install
#
#          cd ..
#          pip install twine wheel
#          python3 -m pip install -e .
#          python3 setup.py bdist
#      - name: Install necessary dependencies (MacOS)
#        if: ${{ !startsWith(matrix.python-version, 'pypy') && startsWith(matrix.os, 'macos') }}
#        run: |
#          brew install gmp
#          brew install mpfr
#          brew install libmpc
#          brew install eigen
#          brew install eigenpy
#          brew install boost
#          brew install boost-python3
#      - name: Build Executables
#        if: ${{ !startsWith(matrix.python-version, 'pypy') }}
#        run: |
#          pip install numpy scipy
#          cd ${{github.workspace}}/core
#          mkdir build
#          cd build
#          cmake .. -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/b2/build -DCMAKE_PREFIX_PATH=$CONDA_PREFIX
#          make -j 4
#          make install
#
#          cd ${{github.workspace}}/python
#          mkdir build
#          cd build
#          cmake .. -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/b2/build -DCMAKE_PREFIX_PATH=$CONDA_PREFIX
#          make -j 4
#          make install
#
#          cd ..
#          pip install twine wheel
#          python3 -m pip install -e .
#          python3 setup.py bdist
#      - name: Upload Builds
#        uses: actions/upload-artifact@v3
#        with:
#          name: built-binary
#          path: |
#            ${{github.workspace}}/python/dist/*.whl
#            ${{github.workspace}}/python/dist/*.tar.gz
#            ${{github.workspace}}/python/build/*.exe
#            ${{github.workspace}}/python/build/*.bin
      - name: Install necessary dependencies (Posix)
        if: ${{ !startsWith(matrix.python-version, 'pypy') && startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libgmp3-dev libmpfr-dev libmpc-dev libeigen3-dev automake autoconf libtool build-essential tar
          pip install setuptools
      - name: Install necessary dependencies (MacOS)
        if: ${{ !startsWith(matrix.python-version, 'pypy') && startsWith(matrix.os, 'macos') }}
        run: |
          brew install gmp
          brew install mpfr
          brew install libmpc
          brew install eigen
          brew install eigenpy
          brew install boost
          brew install boost-python3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache boost packages
        id: cache-boost
        if: ${{ !startsWith(matrix.python-version, 'pypy') && startsWith(matrix.os, 'ubuntu') }}
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cache-boost-ubuntu
          path: |
            ${{github.workspace}}/boost
      - name: Install Boost
        if: ${{ steps.cache-boost.outputs.cache-hit != 'true' && !startsWith(matrix.python-version, 'pypy') && startsWith(matrix.os, 'ubuntu') }}
        run: |
          wget https://archives.boost.io/release/1.87.0/source/boost_1_87_0.tar.gz
          tar xvfz boost_1_87_0.tar.gz
          cd boost_1_87_0
          ./bootstrap.sh --with-python=$(which python3) --prefix=${{github.workspace}}/boost
          ./b2 install
      - name: Checkout and install eigen
        if: ${{ !startsWith(matrix.python-version, 'pypy') && startsWith(matrix.os, 'ubuntu') }}
        run: |
          git clone https://gitlab.com/libeigen/eigen.git
          cd eigen
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/b2/build -DCMAKE_PREFIX_PATH=${{github.workspace}}/boost
          make -j 4
          make install
      - name: Checkout eigenpy
        uses: actions/checkout@v2
        with:
          repository: stack-of-tasks/eigenpy
          path: './eigenpy'
      - name: Install eigenpy
        if: ${{ !startsWith(matrix.python-version, 'pypy') && startsWith(matrix.os, 'ubuntu') }}
        run: |
          pip install numpy scipy
          cd eigenpy
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/b2/build -DCMAKE_PREFIX_PATH=${{github.workspace}}/boost
          make -j 4
          make install
      - name: Build Executables
        if: ${{ !startsWith(matrix.python-version, 'pypy') && !startsWith(matrix.os, 'windows') }}
        run: |
          pip install numpy scipy
          cd ${{github.workspace}}/core
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/b2/build -DCMAKE_PREFIX_PATH=${{github.workspace}}/boost
          make -j 4
          make install

          cd ${{github.workspace}}/python
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/b2/build -DCMAKE_PREFIX_PATH=${{github.workspace}}/boost
          make -j 4
          make install

          cd ..
          pip install twine wheel
          python3 -m pip install -e .
          python3 setup.py bdist
      - uses: conda-incubator/setup-miniconda@v3
        if: ${{ !startsWith(matrix.python-version, 'pypy') && startsWith(matrix.os, 'windows')}}
        with:
          activate-environment: b2
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - name: Build (Windows)
        if: ${{ !startsWith(matrix.python-version, 'pypy') && startsWith(matrix.os, 'windows')}}
        shell: powershell
        run: |
          conda info
          conda list
          cd $env:GITHUB_WORKSPACE\core
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=$env:GITHUB_WORKSPACE\b2\build -DCMAKE_PREFIX_PATH=$env:CONDA_PREFIX\Library
          make -j 4
          make install

          cd $env:GITHUB_WORKSPACE\python
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=$env:GITHUB_WORKSPACE\b2\build -DCMAKE_PREFIX_PATH=$env:CONDA_PREFIX\Library
          make -j 4
          make install

          cd ..
          pip install twine wheel
          python3 -m pip install -e .
          python3 setup.py bdist
      - name: Upload Builds (Posix)
        uses: actions/upload-artifact@v3
        if: ${{ !startsWith(matrix.python-version, 'pypy') }}
        with:
          name: built-binary
          path: |
            ${{github.workspace}}/python/dist/*.whl
            ${{github.workspace}}/python/dist/*.tar.gz
            ${{github.workspace}}/python/build/*.exe
            ${{github.workspace}}/python/build/*.bin
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: built-binary

      - name: Check Version
        uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: 'v'

      - name: Check for Pre-Release
        uses: haya14busa/action-cond@v1
        id: is_prerelease
        with:
          cond: ${{ steps.version.outputs.prerelease != '' }}
          if_true: true
          if_false: false

      - name: Get Newest Changelog
        run: |
          python -c "import re; from pathlib import Path; text=re.sub('<!--(.*?)-->', '', (Path.cwd() / 'CHANGELOG.md').read_text(), flags=re.DOTALL); start=text.find('_' * 79); (Path.cwd() / 'TEMP_CHANGELOG.md').write_text(text[start:text.find('_' * 79, start+1)])"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ steps.is_prerelease.outputs.value }}
          body_path: ./TEMP_CHANGELOG.md
            python/dist/*.whl
            python/dist/*.tar.gz
            python/build/*.exe
            python/build/*.bin


#      - name: Install pypa/build
#        run: >-
#          python3 -m
#          pip install
#          build
#          --user
#      - name: Build a binary wheel and a source tarball
#        run: python3 -m build
#      - name: Store the distribution packages
#        uses: actions/upload-artifact@v4
#        with:
#          name: python-package-distributions
#          path: dist/

#  publish-to-pypi:
#    name: >-
#      Publish Python 🐍 distribution 📦 to PyPI
#    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
#    needs:
#      - build
#    runs-on: ubuntu-latest
#    environment:
#      name: pypi
#      url: https://pypi.org/p/<package-name>  # Replace <package-name> with your PyPI project name
#    permissions:
#      id-token: write  # IMPORTANT: mandatory for trusted publishing
#
#    steps:
#      - name: Download all the dists
#        uses: actions/download-artifact@v4
#        with:
#          name: python-package-distributions
#          path: dist/
#      - name: Publish distribution 📦 to PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1
#
#  github-release:
#    name: >-
#      Sign the Python 🐍 distribution 📦 with Sigstore
#      and upload them to GitHub Release
#    needs:
#      - publish-to-pypi
#    runs-on: ubuntu-latest
#
#    permissions:
#      contents: write  # IMPORTANT: mandatory for making GitHub Releases
#      id-token: write  # IMPORTANT: mandatory for sigstore
#
#    steps:
#      - name: Download all the dists
#        uses: actions/download-artifact@v4
#        with:
#          name: python-package-distributions
#          path: dist/
#      - name: Sign the dists with Sigstore
#        uses: sigstore/gh-action-sigstore-python@v3.0.0
#        with:
#          inputs: >-
#            ./dist/*.tar.gz
#            ./dist/*.whl
#      - name: Create GitHub Release
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
#        run: >-
#          gh release create
#          "$GITHUB_REF_NAME"
#          --repo "$GITHUB_REPOSITORY"
#          --notes ""
#      - name: Upload artifact signatures to GitHub Release
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
#        # Upload to GitHub Release using the `gh` CLI.
#        # `dist/` contains the built packages, and the
#        # sigstore-produced signatures and certificates.
#        run: >-
#          gh release upload
#          "$GITHUB_REF_NAME" dist/**
#          --repo "$GITHUB_REPOSITORY"
#
#  publish-to-testpypi:
#    name: Publish Python 🐍 distribution 📦 to TestPyPI
#    needs:
#      - build
#    runs-on: ubuntu-latest
#
#    environment:
#      name: testpypi
#      url: https://test.pypi.org/p/<package-name>
#
#    permissions:
#      id-token: write  # IMPORTANT: mandatory for trusted publishing
#
#    steps:
#      - name: Download all the dists
#        uses: actions/download-artifact@v4
#        with:
#          name: python-package-distributions
#          path: dist/
#      - name: Publish distribution 📦 to TestPyPI
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          repository-url: https://test.pypi.org/legacy/
